# 指定运行环境为 node
language: node_js

# 指定 nodejs 版本
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'

# 指定分支，只有指定的分支提交时才会运行脚本
branchs:
  only:
    - master

# 安装依赖之前，先升级 yarn 版本
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"

# 安装依赖
install:
  - yarn

# 缓存 node_js 依赖，提升第二次构建的效率
cache:
  directories:
    - node_modules
    - $HOME/.cache/yarn
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs

# 运行的脚本命令
script:
  - yarn test:coverage # 单元测试并收集测试覆盖信息

# 阶段成功时执行
after_success:
  - yarn codecov # 将单元测试结果上传到 codecov

# 在多个操作系统上运行
os:
  - linux
  - osx